News_Portal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),  # Подключаем URL-ы allauth
]

news/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (ArticlesCreate, ArticlesDelete, ArticlesDetailView,
                    ArticlesListView, ArticlesUpdate, CategoryDetailView,
                    CategoryListView, NewsCreate, NewsDelete, NewsDetailView,
                    NewsListView, NewsUpdate, PostListView, PostSearchView,
                    profile_view, subscribe_to_category, upgrade_me)

app_name = 'news'

urlpatterns = [
    # path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', profile_view, name='profile_view'),
    path('upgrade/', upgrade_me, name= 'upgrade'),
    path('post/', cache_page(60*5)(PostListView.as_view()), name='post_list'), # Общий список
    path('post/news/', cache_page(60*5)(NewsListView.as_view()), name='news_list'), # Cписок новостей
    path('post/news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'), # Детализация новости
    path('post/news/search/', PostSearchView.as_view(), name='search'), # Поиск
    path('post/news/create/', NewsCreate.as_view(), name='news_create'), # Создание новостей
    path('post/news/<int:pk>/update/', NewsUpdate.as_view(), name='news_update'), # Редактирование новостей
    path('post/news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'), # Подтверждение удаления новости
    path('post/articles/', cache_page(60*5)(ArticlesListView.as_view()), name='articles_list'), # Список статей
    path('post/articles/<int:pk>/', ArticlesDetailView.as_view(), name='articles_detail'), # Детализация статьи
    path('post/articles/create', ArticlesCreate.as_view(), name='articles_create'), # Создание статьи
    path('post/articles/<int:pk>/update/', ArticlesUpdate.as_view(), name='articles_update'), # Редактирование статьи
    path('post/articles/<int:pk>/delete/', ArticlesDelete.as_view(), name='articles_delete'), # Подтверждение удаления статьи
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/<int:category_id>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/<int:category_id>/subscribe/', subscribe_to_category, name='subscribe_to_category'),    
]

news/models.py
from datetime import date

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)

    def upgrade_rating(self):
        post_ratings = sum(post.rating * 3 for post in self.post_set.all())
        comment_ratings = sum(comment.rating for comment in Comment.objects.filter(user=self.user))
        author_comment_ratings = sum(comment.rating for post in self.post_set.all() for comment in Comment.objects.filter(post=post))
        self.rating = post_ratings + comment_ratings + author_comment_ratings
        self.save()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, related_name='subscribed_categories')

    def __str__(self):
        return self.name
    
class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'
    
    POST_TYPE_CHOICES = [
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=2, choices=POST_TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=200)
    content = models.TextField()
    rating = models.FloatField(default=0)

    def preview(self):
        return self.content[:124] + '...' if len(self.content) > 124 else self.content

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return self.title  
    
    def get_absolute_url(post):
        if post.post_type == 'NW':
            return reverse("news:news_detail", args=[str(post.id)])
        else:
            return reverse("news:articles_detail", args=[str(post.id)]) 
    
    def _set_categories(self, *args, **kwargs):
            if 'categories' in kwargs:
                categories = kwargs['categories']
                if categories:
                    for category in categories:
                        PostCategory.objects.get_or_create(post=self, category=category)
        
    def send_new_post_notification(self):
        """
        Отправляет уведомление подписчикам категории о создании нового поста.
        """
        for category in self.categories.all():
            for subscriber in category.subscribers.all():
                subject = f"Новый пост в категории {category.name}!"
                message = f"Привет, {subscriber.username}!\n\n"
                message += f"В категории '{category.name}' появился новый пост:\n\n"
                message += f"- {self.title} - {self.get_absolute_url()}\n\n"
                message += "С уважением,\nАдминистрация сайта"
                send_mail(
                    subject=subject,
                    message=message,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[subscriber.email],
                    fail_silently=False
                )

    def save(self, *args, **kwargs):
        # Проверка количества публикаций в день
        created_at = date.today()
        if self.author:
            last_posts = Post.objects.filter(
                author=self.author, created_at=created_at
            ).count()
            if last_posts >= 3:
                raise ValidationError(
                    "Вы можете публиковать не более трёх новостей в день."
                )

        self._set_categories(*args, **kwargs)
        super().save(*args, **kwargs)
        self.send_new_post_notification.delay(self.pk) 
            
class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['post', 'category']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.title}'

class BadWord(models.Model):
    word = models.CharField(max_length=255)

    def __str__(self):
        return self.word

news/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User
from django.core.exceptions import ValidationError

from .models import Post


class UserRegistrationForm(UserCreationForm): # Форма регистрации
    email = forms.EmailField()    
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class PostForm(forms.ModelForm): # Форма для поиска
    class Meta:
        model = Post
        fields = [
            'author',
            'categories',
            'title',
            'content',
        ]

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')
        if content is not None and len(content) < 20:
            raise ValidationError({
                'content': "Описание не может содержат менее 20 символов"
            })
        
        name = cleaned_data.get('title')
        if name == content:
            raise ValidationError(
                "Описание не может быть идентично названию"
            )
        if name[0].islower():
            raise ValidationError(
                "Название должно быть с заглавной буквы"
            )
        return cleaned_data

class BasicSingupForm(SignupForm):

    def save(self, request):
        user = super(BasicSingupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user

news/views.py
from datetime import date, timedelta

from celery import shared_task
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.db.models.base import Model as Model
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from .filters import PostFilter
from .forms import PostForm
from .models import Category, Post


class PostListView(ListView): # Представление для вывода общего списка
    model = Post
    template_name = 'post_list.html' # Путь к шаблону
    context_object_name = 'posts' # Имя переменной которая будет использоваться в шаблоне 
    ordering = ['-created_at'] # Сортировка от новых к старым
    paginate_by = 10 # Укажите кол-во постов на 1 странице

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = self.get_queryset().count # Кол-во постов
        context['year'] = timezone.now().year # Текущий год
        return context

class NewsListView(ListView): # Представление для вывода списка новостей
    model = Post
    template_name = 'news/news_list.html' # Путь к шаблону
    context_object_name = 'posts' # Имя переменной которая будет использоваться в шаблоне 
    ordering = ['-created_at'] # Сортировка от новых к старым
    paginate_by = 10 # Укажите кол-во постов на 1 странице

    def get_queryset(self): # Фильтр только новости
        return Post.objects.filter(post_type__in =['Новость', 'NW'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_count'] = self.get_queryset().count # Кол-во постов
        context['year'] = timezone.now().year # Текущий год
        return context
    
class ArticlesListView(ListView): # Представление для вывода списка статей
    model = Post
    template_name = 'articles/articles_list.html' #Путь к шаблону
    context_object_name = 'posts' # Имя переменной которая будет использоваться в шаблоне
    ordering = ['-created_at'] # Сортировка от новых к старым
    paginate_by = 10 # Кол-во постов на странице

    def get_queryset(self):
        return Post.objects.filter(post_type__in = ['Статья', 'AR'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles_count'] = self.get_queryset().count # Кол-во постов
        context['year'] = timezone.now().year # Текущий год
        return context

class NewsDetailView(DetailView): #Представление для вывода детализации новости
    model = Post
    template_name = 'news/news_detail.html' # Путь к шаблону
    context_object_name = 'post' # Имя переменной в шаблоне

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        #post = get_object_or_404(Post, id=self.kwargs['post_id'])
        if post.post_type != 'NW' and post.post_type != 'Новость':
           raise Http404('Это не новость!"')
        return post

    def get_context_data(self, **kwargs ):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['categories'] = post.categories.all()
        return context
    
class ArticlesDetailView(DetailView): # Представление для вывода детализации статей
    model = Post
    template_name = 'articles/articles_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        if post.post_type != 'AR' and post.post_type != 'Статья':
            raise Http404("Это не статья!")
        return post

class PostSearchView(ListView): # Представление для поиска
    model = Post
    template_name = 'news/search_result.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filters'] = self.filterset
        return context

class NewsCreate(LoginRequiredMixin, PermissionRequiredMixin,CreateView): # Представление для создания новостей
    permission_required = ('post.add_object', )
    form_class = PostForm
    model = Post
    template_name = 'news/news_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.post_type = 'Новость'
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='author').exists()
        return context

class ArticlesCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView): # Представление для создания статей
    permission_required = ('post.add_object', )
    form_class = PostForm
    model = Post
    template_name = 'articles/articles_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.post_type = 'Статья'
        return super().form_valid(form) 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='author').exists()
        return context

class NewsUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView): # Представление для создания новостей
    form_class = PostForm
    model = Post
    template_name = 'news/news_edit.html'

    def test_func(self):
        post = self.get_object()  # Получаем объект поста
        return self.request.user == post.author or self.request.user.is_staff

class ArticlesUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView): # Представление для изменения статей
    form_class = PostForm
    model = Post
    template_name = 'articles/articles_edit.html'

    def test_func(self):
        post = self.get_object()  # Получаем объект поста
        return self.request.user == post.author or self.request.user.is_staff

class NewsDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView): # Представление для удаления новостей
    model = Post
    template_name = 'news/news_delete.html'
    success_url = reverse_lazy('news:news_list')

    def test_func(self):
        post = self.get_object()  # Получаем объект поста
        return self.request.user == post.author or self.request.user.is_staff

class ArticlesDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView): # Представление для удаления статей
    model = Post
    template_name = 'articles/articles_delete.html'
    success_url = reverse_lazy('news:articles_list')

    def test_func(self):
        post = self.get_object()  # Получаем объект поста
        return self.request.user == post.author or self.request.user.is_staff

class CategoryListView(ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category_detail.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.post_set.all()
        return context
    
@login_required
def upgrade_me(request):
    user = request.user
    author_group = Group.objects.get(name='author')
    if not user.groups.filter(name='author').exists():
        author_group.user_set.add(user)
    return redirect('/post/')

@login_required
def profile_view(request):
    user = request.user
    is_author = user.groups.filter(name='author').exists()

    return render(request, 'post_list.html', {'is_author': is_author})

@login_required
def subscribe_to_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.user.is_authenticated:
        if request.user in category.subscribers.all():
            category.subscribers.remove(request.user)
            message = "Вы отписались от этой категории."
        else:
            category.subscribers.add(request.user)
            message = "Вы подписались на эту категорию!"
        return redirect('news:category_list')
    else:
        return redirect('login')  # Перенаправьте на страницу входа, если пользователь не авторизован

news/templates/category_detail.html
{% extends "default.html" %}
{% block content %}
    <h1>{{ category.name }}</h1>
    <ul>
        {% for post in posts %}
            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

news/templates/category_list.html
{% extends 'default.html' %} 

{% block content %}
    <h1>Список категорий</h1>
    <ul>
        {% for category in categories %}
            <li>
                <h2><a href="{% url 'news:category_detail' category_id=category.pk %}">{{ category.name }}</a></h2>
                <a href="{% url 'news:subscribe_to_category' category_id=category.pk %}">
                    {% if user in category.subscribers.all %}
                        Отписаться
                    {% else %}
                        Подписаться
                    {% endif %}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

news/templates/default.html
<html lang="ru">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type='text/css' href="{% static 'styles.css' %}">  <!-- Подключение стилей -->
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>
    {% load cache %}
        {% cache 30 header %}
        <header>
            <h1>Мой веб-сайт</h1>
            <nav>
                <ul style="list-style: none; display: flex; justify-content: flex-end; padding: 0; margin: 0;">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Выход</a></li>
                    {% else %}
                        <li><a href="{% url 'account_login' %}">Вход</a></li>
                        <li><a href="{% url 'account_signup' %}">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'news:post_list' %}">Главная страница</a></li>
                </ul>
            </nav>
        </header>
    {% endcache %}
    
    <main>
        {% block content %}
                <!-- Содержимое страницы будет отображаться здесь -->
        {% endblock %}
    </main>

    <footer>
        <q>© {{ year }} Мой веб-сайт</q>
    </footer>
</body>
</html>

news/templates/news_email.html
<h1>{{ title }}</h1>
<p>{{ content }}</p>

news/templates/post_list.html
{% extends "default.html" %}
{% load custom_filter %}

{% block title %}Новости{% endblock %}
{% block nav_links %}

{% endblock %}

{% block content %}
{% if not is_author %}
<form action="{% url 'news:upgrade' %}" method="post">
    {% csrf_token %}
    <button type="submit">Стать автором</button>
</form>
{% endif %}
    <h2>Главная страница</h2>

    <h3>Всего постов: {{post_count }}</h3>
    
    <form action="{% url 'news:search' %}" method="get">
        <input type="text" name="title" placeholder="Поиск по названию...">
        <input type="text" name="author" placeholder="Поиск по автору...">
        <input type="date" name="created_at">
        <button type="submit">Поиск</button>
    </form>

    <ul>
        {% if posts %}
            {% for post in posts %}
                <article>
                    <h3>
                        <a href="{% if post.post_type == 'Новость' or post.post_type == 'NW' %}{% url 'news:news_detail' post.pk %}{% else %}{% url 'news:articles_detail' post.pk %}{% endif %}">
                            {{ post.title|censor }}
                        </a>
                    </h3>
                    <p>Post PK:{{ post.pk}}</p>
                    <p><strong>Дата публикации:</strong> {{ post.created_at|date:"d.m.Y" }}</p>
                    <p>{{ post.preview|truncatewords:20|censor }}...</p>  
                    {% if post.content|length > 30 %}
                        <p>
                            <a href="{% if post.post_type == 'Новость' or post.post_type == 'NW' %}{% url 'news:news_detail' post.pk %}{% else %}{% url 'news:articles_detail' post.pk %}{% endif %}">
                                Читать далее
                            </a>
                        </p>
                    {% endif %}
                </article>
            {% endfor %}
        {% else %}
            <p>Нет новостей.</p>
        {% endif %}
    </ul>
    {# Добавляем прогинацию на страницу #}
    {# Информация о предыдущей странице #}
    {% if page_obj.has_previous %}
        <a href='?page=1' >1</a>
        {% if page_obj.has_previous_page_number != 1%}
            ...
            <a href="?page={{ page_obj.has_previous_page_number }}"> {{ page_obj.has_previous_page_number}} </a>
        {%  endif %}
    {% endif %}
    {# Информация о текущей странице #}
    {{ page_obj.number }}
    {#Информация о текущей следующей странице #}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}
{% endblock content%}

news/templates/weekly_newsletter.html
<h1>Новые статьи в категории {{ category.name }}</h1>
<ul>
  {% for post in new_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
<p>Здравствуй, {{ user.username }}!  </p>